### ISSUE TITLE
Using your pushover-client 

### ISSUE THREAD

**Issue by bengivre** [cburkins/pushover-client#1]
Hi, 
thanks for starting this project. 
I'm very interested by having a client that will receive notification from pushover service. 
I would like to use and contribute to this project , can you tell us more details on the configuration file and maybe the requirement on pushover side ? A token , an api key or something ? 

My idea is to be able to take actions on pushover notification . 
To be more specific,   I have an monitoring system that send pushover notification. 
I'm having a raspberry pi (w) that will be a client of pushover notification.  
When the device receive a notification,  the device will take actions : (examples) 
- Turn on a red light  
- Play a sound or a song like mp3 
- etc...  

The client could start , connect to the service , send a pushover test message to a specific groupe to "initialise" and tel the client something like "ready to receive notifications"  , or maybe just a simple email. 
Using raspberry pi, this should be user friendly without a screen :)  

Let met know what do you think
Regards,

**Comment by bengivre** [comment]
Any idea ?

**Comment by cburkins** [comment]
Hi givre (Benoit?), just saw your message.... would be happy to document a few things here for you.  And yes, it's working :)

**Comment by bengivre** [comment]
Hi,
Thanks for you answer  :) 
Yes I would appreciate it and will be happy to share more about what I would use this for. 

Edit: Just saw the doc ! Thanks a lot. I will test all of that :)

Regards, 
Benoit.

**Comment by cburkins** [comment]
Hi Benoit, have a look at the readme.md and let me know if you've got any
questions not answered there.  (or if I made any mistakes in the
description)
