### ISSUE TITLE
get the notification title if one exist

### ISSUE THREAD

**Issue by bengivre** [cburkins/pushover-client#2]
Hi, 
Do you think it's technically possible to get the content of "notification title" if there is one?
Thanks

**Comment by cburkins** [comment]
Let me take a look and see.....

**Comment by cburkins** [comment]
Yup. I can see the title within the JSON data structure being returned from the API.  I'll open up a branch to do a quick-and-dirty extraction of it, then merge it to master once I get it cleaned up.

**Comment by cburkins** [comment]
OK, works now.  You can send the title via pushoverSend, and pushOverListen will extract the title and print to the command-line.

**Comment by bengivre** [comment]
Just to confirm, it works well :) 
Thanks !

**Comment by cburkins** [comment]
That's great, I'm glad !  Appreciate you letting me know, rather gratifying.
